### ISSUE TITLE
[RoadMap] - TensorLayer 2.0

### ISSUE THREAD

**Issue by DEKHTIARJonathan** [tensorlayer/tensorlayer#860]
# NETWORK API REFACTORING - TO DO LIST

## Finished work:

<details>

- **activation.py:**
  * PReluLayer:
    - [x] refactored
    - [x] tested
  * PRelu6Layer:
    - [x] refactored
    - [x] tested
  * PTRelu6Layer:
    - [x] refactored
    - [x] tested
- **convolution/**
  * AtrousConv1dLayer:
    - [ ] refactored => Need to be implemented
    - [ ] tested
  * AtrousConv2dLayer:
    - [x] refactored
    - [x] tested
  * AtrousDeConv2dLayer:
    - [x] refactored
    - [x] tested
  * BinaryConv2d:
    - [x] refactored
    - [x] tested
  * Conv1d:
    - [x] refactored
    - [x] tested
  * Conv2d:
    - [x] refactored
    - [x] tested
  * Conv1dLayer:
    - [x] refactored
    - [x] tested
  * Conv2dLayer:
    - [x] refactored
    - [x] tested
  * Conv3dLayer:
    - [x] refactored
    - [x] tested
  * DeConv2d:
    - [x] refactored
    - [x] tested
  * DeConv3d:
    - [x] refactored
    - [x] tested
  * DeConv2dLayer:
    - [x] refactored
    - [x] tested
  * DeConv3dLayer:
    - [x] refactored
    - [x] tested
  * DeformableConv2d:
    - [x] refactored
    - [x] tested
  * DepthwiseConv2d:
    - [x] refactored
    - [x] tested
  * DorefaConv2d:
    - [x] refactored
    - [x] tested
  * GroupConv2d:
    - [x] refactored
    - [x] tested
  * QuantizedConv2d:
    - [x] refactored
    - [x] tested
  * QuantizedConv2dWithBN:
    - [x] refactored
    - [x] tested
  * SeparableConv1d:
    - [x] refactored
    - [x] tested
  * SeparableConv2d:
    - [x] refactored
    - [x] tested
  * SubpixelConv1d:
    - [x] refactored
    - [x] tested
  * SubpixelConv2d:
    - [x] refactored
    - [x] tested
  * TernaryConv2d:
    - [x] refactored
    - [x] tested
- **dense/**
  * BinaryDenseLayer:
    - [x] refactored
    - [x] tested
  * DenseLayer:
    - [x] refactored
    - [x] tested
  * DorefaDenseLayer:
    - [x] refactored
    - [x] tested
  * DropconnectDenseLayer:
    - [x] refactored
    - [x] tested
  * QuantizedDense:
    - [x] refactored
    - [x] tested
  * QuantizedDenseWithBN:
    - [x] refactored
    - [x] tested
  * TernaryDenseLayer:
    - [x] refactored
    - [x] tested
- **dropout.py**
  * DropoutLayer:
    - [x] refactored
    - [x] tested
- **extend.py**
  * ExpandDimsLayer:
    - [x] refactored
    - [x] tested
  * TileLayer:
    - [x] refactored
    - [x] tested
- **image_resampling.py**
  * UpSampling2dLayer:
    - [x] refactored
    - [x] tested
  * DownSampling2dLayer:
    - [x] refactored
    - [x] tested
- **importer.py**
  * SlimNetsLayer:
    - [x] refactored
    - [x] tested
  * KerasLayer:
    - [x] refactored
    - [x] tested
- **inputs.py**
  * InputLayer:   
    - [x] refactored
    - [x] tested
  * OneHotInputLayer:   
    - [x] refactored
    - [x] tested
  * Word2vecEmbeddingInputlayer:   
    - [x] refactored
    - [x] tested
  * EmbeddingInputlayer:   
    - [x] refactored
    - [x] tested
  * AverageEmbeddingInputlayer:  
    - [x] refactored
    - [x] tested
- **lambda_layers.py**
  * ElementwiseLambdaLayer:
    - [x] refactored
    - [x] tested
  * LambdaLayer:   
    - [x] refactored  
    - [x] tested
- **merge.py**
  * ConcatLayer:   
    - [x] refactored
    - [x] tested
  * ElementwiseLayer:
    - [x] refactored
    - [x] tested
- **noise.py**
  * GaussianNoiseLayer:   
    - [x] refactored
    - [x] tested
- **normalization.py**
  * BatchNormLayer:   
    - [x] refactored
    - [x] tested
  * GroupNormLayer:
    - [x] refactored
    - [x] tested
  * InstanceNormLayer:   
    - [x] refactored
    - [x] tested
  * LayerNormLayer:   
    - [x] refactored
    - [x] tested
  * LocalResponseNormLayer:   
    - [x] refactored
    - [x] tested
  * SwitchNormLayer:   
    - [x] refactored
    - [x] tested
- **padding.py**
  * PadLayer:   
    - [x] refactored
    - [x] tested
  * ZeroPad1d:   
    - [x] refactored
    - [x] tested
  * ZeroPad2d:   
    - [x] refactored
    - [x] tested
  * ZeroPad3d:  
    - [x] refactored
    - [x] tested
- **pooling/**
    * MaxPool1d:  
      - [x] refactored
      - [x] tested
    * MaxPool2d:  
      - [x] refactored
      - [x] tested
    * MaxPool3d:  
      - [x] refactored
      - [x] tested
    * MeanPool1d:  
      - [x] refactored
      - [x] tested
    * MeanPool2d:  
      - [x] refactored
      - [x] tested
    * MeanPool3d:  
      - [x] refactored
      - [x] tested
    * GlobalMaxPool1d:
      - [x] refactored
      - [x] tested
    * GlobalMaxPool2d:  
      - [x] refactored
      - [x] tested
    * GlobalMaxPool3d:  
      - [x] refactored
      - [x] tested
    * GlobalMeanPool1d:  
      - [x] refactored
      - [x] tested
    * GlobalMeanPool2d:
      - [x] refactored
      - [x] tested
    * GlobalMeanPool3d:
      - [x] refactored
      - [x] tested
    * PoolLayer:
      - [x] refactored
      - [x] tested
- **quantize_layers.py**
  * SignLayer:
    - [x] refactored
    - [x] tested
- **recurrent/**
  * BiDynamicRNNLayer:
    - [x] refactored
    - [x] tested
  * BiRNNLayer:
    - [x] refactored
    - [x] tested
  * ConvLSTMLayer:
    - [x] refactored
    - [x] tested
  * DynamicRNNLayer:
    - [x] refactored
    - [x] tested
  * RNNLayer:
    - [x] refactored
    - [x] tested
  * Seq2Seq:
    - [x] refactored
    - [x] tested
- **reshape.py**
  * FlattenLayer:
    - [x] refactored
    - [x] tested
  * ReshapeLayer:
    - [x] refactored
    - [x] tested
  * TransposeLayer:
    - [x] refactored
    - [x] tested
- **scale.py**
  * ScaleLayer:
    - [x] refactored
    - [x] tested
</details>

## Unittests Status:

- test_activations.py
    - [ ] refactored
    - [x] tested
- test_array_ops.py
    - [x] refactored
    - [x] tested
- test_decorators.py
    - [x] refactored
    - [x] tested
- test_documentation.py
    - [x] refactored
    - [x] tested
- test_layers_activation.py
    - [x] refactored
    - [x] tested
- test_layers_basic.py
    - [x] refactored
    - [ ] tested
- test_layers_convolution_1d.py
    - [x] refactored
    - [ ] tested
- test_layers_convolution_2d.py
    - [x] refactored
    - [ ] tested
- test_layers_convolution_3d.py
    - [x] refactored
    - [ ] tested
- test_layers_convolution_deformable.py
    - [x] refactored
    - [ ] tested
- test_layers_core.py
    - [x] refactored
    - [ ] tested
- test_layers_extend.py
    - [x] refactored
    - [ ] tested
- test_layers_flow_control.py  **removed** in favour of eager mode
- test_layers_importer.py
    - [x] refactored
    - [ ] tested
- test_layers_merge.py
    - [x] refactored
    - [ ] tested
- test_layers_normalization.py
    - [x] refactored
    - [ ] tested
- test_layers_padding.py
    - [x] refactored
    - [ ] tested
- test_layers_pooling.py
    - [x] refactored
    - [ ] tested
- test_layers_recurrent.py
    - [x] refactored
    - [ ] tested
- test_layers_reshape.py
    - [x] refactored
    - [ ] tested
- test_layers_spatial_transformer.py
    - [x] refactored
    - [ ] tested
- test_layers_stack.py
    - [x] refactored
    - [ ] tested
- test_layers_super_resolution.py
    - [x] refactored
    - [ ] tested
- test_layers_time_distributed.py
    - [x] refactored
    - [ ] tested
- test_logging.py
    - [x] refactored
    - [x] tested
- test_logging_hyperdash.py
    - [x] refactored
    - [x] tested
- test_mnist_simple.py
    - [x] refactored
    - [ ] tested
- test_model_compilednetwork.py
    - [x] refactored
    - [ ] tested
- test_models.py
    - [x] refactored
    - [ ] tested
- test_network_custom_2d.py
    - [x] refactored
    - [x] tested
- test_network_custom_input_layers.py
    - [x] refactored
    - [x] tested
- test_network_custom_multiple_inputs.py
    - [x] refactored
    - [x] tested
- test_network_custom_multiple_outputs.py
    - [x] refactored
    - [x] tested
- test_network_sequential_1d.py
    - [x] refactored
    - [x] tested
- test_network_sequential_2d.py
    - [x] refactored
    - [x] tested
- test_network_sequential_3d.py
    - [x] refactored
    - [x] tested
- test_network_sequential_rnn.py
    - [x] refactored
    - [x] tested
- test_optimizer_amsgrad.py
    - [x] refactored
    - [ ] tested
- test_pydocstyle.py
    - [ ] refactored
    - [ ] tested
- test_reuse_mlp.py
    - [x] refactored
    - [ ] tested
- test_tf_layers.py
    - [x] refactored
    - [ ] tested
- test_timeout.py
    - [x] refactored
    - [x] tested
- test_utils_predict.py
    - [x] refactored
    - [ ] tested
- test_yapf_format.py
    - [x] refactored
    - [x] tested

### Layers

- **contrib**
  * ROIPoolingLayer:   
    - [x] refactored
    - [ ] tested
- **convolution/**
  * AtrousConv1dLayer:
    - [x] refactored => AtrousConv1dLayer and AtrousConv2dLayer are removed, use Conv1d/2d with `dilation_rate` instead.
    - [x] tested
- **spatial_transformer.py**
  * SpatialTransformer2dAffineLayer:   see **test_layers_spatial_transformer.py**
    - [x] refactored
    - [x] tested
- **stack.py**
  * StackLayer:
    - [x] refactored
    - [ ] tested
  * UnStackLayer: => Need to be checked! Not working
    - [ ] refactored
    - [ ] tested
- **time_distribution.py**
  * TimeDistributedLayer:
    - [x] refactored
    - [ ] tested

### TensorLayer Hub

- **tl.models** => became **tl.hub**
  - [ ] VGG16
  - [ ] VGG19
  - [ ] MobileNet
  - [ ] SqueezeNet

### Examples
- **basic_tutorials**
    - [x] refactored
    - [ ] tested
- **data_process**
    - [x] refactored
    - [x] tested
- **database**
    - [x] refactored
    - [ ] tested
- **deprecated_tutorials**
    - [ ] refactored
    - [ ] tested
- **distributed_training**
    - [x] refactored
    - [ ] tested
- **keras_tfslim**
    - [x] refactored
    - [ ] tested
- **pretrained_cnn**
    - [x] refactored
    - [ ] tested
- **quantized_net**
    - [x] refactored
    - [ ] tested
- **reinforcement_learning**
    - [x] refactored
    - [ ] tested
- **text_classification**
    - [x] refactored
    - [ ] tested
- **text_generation**
    - [x] refactored
    - [ ] tested
- **text_ptb**
    - [x] refactored
    - [ ] tested
- **text_word_embedding**
    - [x] refactored
    - [ ] tested

## More TODO
- [ ] add `scope_name` into the layer name
- [ ] don't check duplicated layer name in core layer

- Test code:

```python
plh = tf.placeholder(tf.float16, (100, 32))
net = tl.layers.InputLayer(name='in')(plh)
with tf.variable_scope('test'):
    net = tl.layers.DenseLayer(n_units=50, act=tf.nn.relu, name="dense")(net)
with tf.variable_scope('test', reuse=True):
    net = tl.layers.DenseLayer(n_units=50, act=tf.nn.relu, name="dense")(net)
print(net['test/dense'])
print(net['test/dense_2'])
assert len(net.all_weights) == 2
print(net.all_params)  # give a warning, but still works
```

- How to do with manual-compile?:

```python
with tf.variable_scope('test'):
    model.add(tl.layers.DenseLayer(n_units=50, act=tf.nn.relu, name="seq_layer_9"))
with tf.variable_scope('test', reuse=True):
    model.add(tl.layers.DenseLayer(n_units=50, act=tf.nn.relu, name="seq_layer_9"))
plh = tf.placeholder(tf.float16, (100, 32))
net = model.build(plc)
print(net['test/seq_layer_9'])
```

- Rename
   - [ ] `assign_params` --> `assign_weights`
   - [ ] `print_params` --> `print_weights`
   - [ ] `print_layers` --> `print_outputs`
   - [ ] `all_layers` --> `all_outputs`
   - [ ] `all_params` --> `all_weights`
   - [ ] `local_weights`
   - [ ] `count_pararms` --> `count_all_weights`
   - [ ] `count_local_weights`
   - [ ] `restore_params` --> `restore_weights`  in `tl.models/hub`
   - [ ] `get_layers_with_name` --> `get_outputs_with_name` ?

Give exception and hint when users use the old name.

- Documentation
   - [ ] docs in python code
   - [ ] docs in RST

- Simplify layer name
    - [x] test folder
    - [x] layer folder
    - [x] example folder
    -  for example,`DenseLayer` --> `Dense` then add code:
```python
def DenseLayer(*args, **kwargs):
    raise Exception("DenseLayer(net, 100) --> Dense(100)(net)")

def BatchNormLayer(*args, **kwargs):
    raise Exception("BatchNormLayer(net, is_train=True, name='bn') --> BatchNorm(name='bn')(net, is_train=True)")
```

**Comment by zsdonghao** [comment]
# NETWORK API REFACTORING - TO DO LIST

@DEKHTIARJonathan As we discussed previously, TensorLayer 2.0 should support both eager and graph mode. The new API design is here https://github.com/luomai/tensorlayer2-design/issues/7

To make the refactoring faster, I simply fork tensorlayer/tensorlayer into zsdonghao/tensorlayer2: https://github.com/zsdonghao/tensorlayer2 , we can merge the branch back to tensorlayer/tensorlayer when refactoring finished. In doing so, the contribution will be in may commits rather than only 1.

## Examples
- basic_tutorials
    - [ ] refactored
    - [ ] tested
- data_process
    - [ ] refactored
    - [ ] tested
- database
    - [ ] refactored
    - [ ] tested
- distributed_training
    - [ ] refactored
    - [ ] tested
- keras_tfslim
    - [ ] refactored
    - [ ] tested
- pretrained_cnn
    - [ ] refactored
    - [ ] tested
- quantized_net
    - [ ] refactored
    - [ ] tested
- pretrained_cnn
    - [ ] refactored
    - [ ] tested
- reinforcement_learning
    - [ ] refactored
    - [ ] tested
- text_classification
    - [ ] refactored
    - [ ] tested
- text_generation
    - [ ] refactored
    - [ ] tested
- text_ptb
    - [ ] refactored
    - [ ] tested
- text_word_embedding
    - [ ] refactored
    - [ ] tested

## Unittests Status:

- test_activations.py
    - [ ] refactored
    - [ ] tested
- test_array_ops.py
    - [ ] refactored
    - [ ] tested
- test_decorators.py
    - [ ] refactored
    - [ ] tested
- test_documentation.py
    - [ ] refactored
    - [ ] tested
- test_layers_activation.py
    - [ ] refactored
    - [ ] tested
- test_layers_basic.py
    - [ ] refactored
    - [ ] tested
- test_layers_convolution_1d.py
    - [ ] refactored
    - [ ] tested
- test_layers_convolution_2d.py
    - [ ] refactored
    - [ ] tested
- test_layers_convolution_3d.py
    - [ ] refactored
    - [ ] tested
- test_layers_convolution_deformable.py
    - [ ] refactored
    - [ ] tested
- test_layers_core.py
    - [ ] refactored
    - [ ] tested
- test_layers_extend.py
    - [x] refactored
    - [ ] tested
- test_layers_flow_control.py  **removed** in favour of eager mode
- test_layers_importer.py
    - [ ] refactored
    - [ ] tested
- test_layers_merge.py
    - [ ] refactored
    - [ ] tested
- test_layers_normalization.py
    - [ ] refactored
    - [ ] tested
- test_layers_padding.py
    - [ ] refactored
    - [ ] tested
- test_layers_pooling.py
    - [ ] refactored
    - [ ] tested
- test_layers_recurrent.py
    - [ ] refactored
    - [ ] tested
- test_layers_reshape.py
    - [ ] refactored
    - [ ] tested
- test_layers_spatial_transformer.py
    - [ ] refactored
    - [ ] tested
- test_layers_stack.py
    - [ ] refactored
    - [ ] tested
- test_layers_super_resolution.py
    - [ ] refactored
    - [ ] tested
- test_layers_time_distributed.py
    - [ ] refactored
    - [ ] tested
- test_logging.py
    - [ ] refactored
    - [ ] tested
- test_logging_hyperdash.py
    - [ ] refactored
    - [ ] tested
- test_mnist_simple.py
    - [ ] refactored
    - [ ] tested
- test_model_compilednetwork.py
    - [ ] refactored
    - [ ] tested
- test_models.py
    - [ ] refactored
    - [ ] tested
- test_network_custom_2d.py
    - [ ] refactored
    - [ ] tested
- test_network_custom_input_layers.py
    - [ ] refactored
    - [ ] tested
- test_network_custom_multiple_inputs.py
    - [ ] refactored
    - [ ] tested
- test_network_custom_multiple_outputs.py
    - [ ] refactored
    - [ ] tested
- test_network_sequential_1d.py
    - [ ] refactored
    - [ ] tested
- test_network_sequential_2d.py
    - [ ] refactored
    - [ ] tested
- test_network_sequential_3d.py
    - [ ] refactored
    - [ ] tested
- test_network_sequential_rnn.py
    - [ ] refactored
    - [ ] tested
- test_optimizer_amsgrad.py
    - [ ] refactored
    - [ ] tested
- test_pydocstyle.py
    - [ ] refactored
    - [ ] tested
- test_reuse_mlp.py
    - [ ] refactored
    - [ ] tested
- test_tf_layers.py
    - [ ] refactored
    - [ ] tested
- test_timeout.py
    - [ ] refactored
    - [ ] tested
- test_utils_predict.py
    - [ ] refactored
    - [ ] tested
- test_yapf_format.py
    - [ ] refactored
    - [ ] tested



## Work to be done

### Layers

- **activation.py:**
  * PRelu:
    - [ ] refactored
    - [ ] tested
  * PRelu6:
    - [ ] refactored
    - [ ] tested
  * PTRelu6:
    - [ ] refactored
    - [ ] tested
- **convolution/**
  * AtrousConv1d:
    - [ ] refactored => Need to be implemented
    - [ ] tested
  * AtrousConv2d:
    - [ ] refactored
    - [ ] tested
  * AtrousDeConv2d:
    - [ ] refactored
    - [ ] tested
  * BinaryConv2d:
    - [ ] refactored
    - [ ] tested
  * Conv1d:
    - [ ] refactored
    - [ ] tested
  * Conv2d:
    - [ ] refactored
    - [ ] tested
  * Conv1dLayer:
    - [ ] refactored
    - [ ] tested
  * Conv2dLayer:
    - [ ] refactored
    - [ ] tested
  * Conv3dLayer:
    - [ ] refactored
    - [ ] tested
  * DeConv2d:
    - [ ] refactored
    - [ ] tested
  * DeConv3d:
    - [ ] refactored
    - [ ] tested
  * DeConv2d:
    - [ ] refactored
    - [ ] tested
  * DeConv3d:
    - [ ] refactored
    - [ ] tested
  * DeformableConv2d:
    - [ ] refactored
    - [ ] tested
  * DepthwiseConv2d:
    - [ ] refactored
    - [ ] tested
  * DorefaConv2d:
    - [ ] refactored
    - [ ] tested
  * GroupConv2d:
    - [ ] refactored
    - [ ] tested
  * QuantizedConv2d:
    - [ ] refactored
    - [ ] tested
  * QuantizedConv2dWithBN:
    - [ ] refactored
    - [ ] tested
  * SeparableConv1d:
    - [ ] refactored
    - [ ] tested
  * SeparableConv2d:
    - [ ] refactored
    - [ ] tested
  * SubpixelConv1d:
    - [ ] refactored
    - [ ] tested
  * SubpixelConv2d:
    - [ ] refactored
    - [ ] tested
  * TernaryConv2d:
    - [ ] refactored
    - [ ] tested
- **dense/**
  * BinaryDense:
    - [ ] refactored
    - [ ] tested
  * Dense:
    - [ ] refactored
    - [ ] tested
  * DorefaDense:
    - [ ] refactored
    - [ ] tested
  * DropconnectDense:
    - [ ] refactored
    - [ ] tested
  * QuantizedDense:
    - [ ] refactored
    - [ ] tested
  * QuantizedDenseWithBN:
    - [ ] refactored
    - [ ] tested
  * TernaryDense:
    - [ ] refactored
    - [ ] tested
- **dropout.py**
  * Dropout:
    - [ ] refactored
    - [ ] tested
- **extend.py**
  * ExpandDims:
    - [ ] refactored
    - [ ] tested
  * Tile:
    - [ ] refactored
    - [ ] tested
- **image_resampling.py**
  * UpSampling2d:
    - [ ] refactored
    - [ ] tested
  * DownSampling2d:
    - [ ] refactored
    - [ ] tested
- **importer.py**
  * SlimNets:
    - [ ] refactored
    - [ ] tested
  * Keras:
    - [ ] refactored
    - [ ] tested
- **inputs.py**
  * Input:   
    - [ ] refactored
    - [ ] tested
  * OneHotInput:   
    - [ ] refactored
    - [ ] tested
  * Word2vecEmbeddingInput:   
    - [ ] refactored
    - [ ] tested
  * EmbeddingInput:   
    - [ ] refactored
    - [ ] tested
  * AverageEmbeddingInput:  
    - [ ] refactored
    - [ ] tested
- **lambda_layers.py**
  * ElementwiseLambda:
    - [ ] refactored
    - [ ] tested
  * Lambda:   
    - [ ] refactored  
    - [ ] tested
- **merge.py**
  * Concat:   
    - [ ] refactored
    - [ ] tested
  * Elementwise:
    - [ ] refactored
    - [ ] tested
- **noise.py**
  * GaussianNoise:   
    - [ ] refactored
    - [ ] tested
- **normalization.py**
  * BatchNorm:   
    - [ ] refactored
    - [ ] tested
  * GroupNorm:
    - [ ] refactored
    - [ ] tested
  * InstanceNorm:   
    - [ ] refactored
    - [ ] tested
  * LayerNorm:   
    - [ ] refactored
    - [ ] tested
  * LocalResponseNorm:   
    - [ ] refactored
    - [ ] tested
  * SwitchNorm:   
    - [ ] refactored
    - [ ] tested
- **padding.py**
  * Pad:   
    - [ ] refactored
    - [ ] tested
  * ZeroPad1d:   
    - [ ] refactored
    - [ ] tested
  * ZeroPad2d:   
    - [ ] refactored
    - [ ] tested
  * ZeroPad3d:  
    - [ ] refactored
    - [ ] tested
- **pooling/**
    * MaxPool1d:  
      - [ ] refactored
      - [ ] tested
    * MaxPool2d:  
      - [ ] refactored
      - [ ] tested
    * MaxPool3d:  
      - [ ] refactored
      - [ ] tested
    * MeanPool1d:  
      - [ ] refactored
      - [ ] tested
    * MeanPool2d:  
      - [ ] refactored
      - [ ] tested
    * MeanPool3d:  
      - [ ] refactored
      - [ ] tested
    * GlobalMaxPool1d:
      - [ ] refactored
      - [ ] tested
    * GlobalMaxPool2d:  
      - [ ] refactored
      - [ ] tested
    * GlobalMaxPool3d:  
      - [ ] refactored
      - [ ] tested
    * GlobalMeanPool1d:  
      - [ ] refactored
      - [ ] tested
    * GlobalMeanPool2d:
      - [ ] refactored
      - [ ] tested
    * GlobalMeanPool3d:
      - [ ] refactored
      - [ ] tested
    * PoolLayer:
      - [ ] refactored
      - [ ] tested
- **quantize_layers.py**
  * Sign:
    - [ ] refactored
    - [ ] tested
- **recurrent/**
  * BiDynamicRNN:
    - [ ] refactored
    - [ ] tested
  * BiRNN:
    - [ ] refactored
    - [ ] tested
  * ConvLSTM:
    - [ ] refactored
    - [ ] tested
  * DynamicRNN:
    - [ ] refactored
    - [ ] tested
  * RNN:
    - [ ] refactored
    - [ ] tested
  * Seq2Seq:
    - [ ] refactored
    - [ ] tested
- **reshape.py**
  * Flatten:
    - [ ] refactored
    - [ ] tested
  * Reshape:
    - [ ] refactored
    - [ ] tested
  * Transpose:
    - [ ] refactored
    - [ ] tested
- **scale.py**
  * Scale:
    - [ ] refactored
    - [ ] tested
- **contrib**
  * ROIPooling:   
    - [ ] refactored
    - [ ] tested
- **convolution/**
  * AtrousConv1d:
    - AtrousConv1dLayer and AtrousConv2dLayer are removed, use Conv1d/2d with `dilation_rate` instead.
- **spatial_transformer.py**
  * SpatialTransformer2dAffine:   see **test_layers_spatial_transformer.py**
    - [ ] refactored
    - [ ] tested
- **stack.py**
  * Stack:
    - [ ] refactored
    - [ ] tested
  * UnStack: => Need to be checked! Not working
    - [ ] refactored
    - [ ] tested
- **time_distribution.py** Remove?
  * TimeDistributed:
    - [ ] refactored
    - [ ] tested

### TensorLayer Hub

- **tl.models** => became **tl.hub**
  - [ ] VGG16
  - [ ] VGG19
  - [ ] MobileNet
  - [ ] SqueezeNet

### Examples
- **basic_tutorials**
    - [x] refactored
    - [ ] tested
- **data_process**
    - [x] refactored
    - [x] tested
- **database**
    - [x] refactored
    - [ ] tested
- **deprecated_tutorials**
    - [ ] refactored
    - [ ] tested
- **distributed_training**
    - [x] refactored
    - [ ] tested
- **keras_tfslim**
    - [x] refactored
    - [ ] tested
- **pretrained_cnn**
    - [x] refactored
    - [ ] tested
- **quantized_net**
    - [x] refactored
    - [ ] tested
- **reinforcement_learning**
    - [x] refactored
    - [ ] tested
- **text_classification**
    - [x] refactored
    - [ ] tested
- **text_generation**
    - [x] refactored
    - [ ] tested
- **text_ptb**
    - [x] refactored
    - [ ] tested
- **text_word_embedding**
    - [x] refactored
    - [ ] tested

## More TODO
- [ ] add `scope_name` into the layer name
- [ ] don't check duplicated layer name in core layer

**Comment by zsdonghao** [comment]
https://github.com/tensorlayer/tensorlayer/issues/900
